plugins:
  - stylelint-prettier
extends:
  - stylelint-config-sass-guidelines
  - stylelint-prettier/recommended
rules:
  max-nesting-depth:
    - 5
    - ignoreAtRules:
        - media
        - supports
        - include
  scss/dollar-variable-pattern: null
  property-no-vendor-prefix: null
  selector-no-qualifying-type: null
