extends: airbnb
env:
    browser: true
    node: true
parser: babel-eslint
rules:
    strict: 0
    object-curly-newline: 0
    jsx-a11y/label-has-for: 0
    jsx-a11y/anchor-is-valid: 0
    jsx-a11y: 0
    react/require-default-props: 0
    react/forbid-prop-types: 0
    react/no-did-mount-set-state: 0
    import/no-extraneous-dependencies: 0
    no-underscore-dangle: 0
settings:
  import/resolver: webpack
